version: '2'
services:
  web:
    build: ./application/.
    ports:
     - "80:80"
    volumes:
     - ./application/back:/ap
     - ./application/public:/ap/templates
     - ./application/resources:/ap/static
    links:
     - db
  db:
    build: ./database/.
    ports:
     - "5432:5432"