version: '2'
services:
  web:
    build: ./backend/.
    ports:
     - "80:80"
    volumes:
     - ./backend:/ap
     - ./backend/templates:/ap/templates
     - ./resources:/ap/static
    links:
     - db
  db:
    build: ./database/.
    volumes:
     - ./database/execSqlFiles:/docker-entrypoint-initdb.d
    ports:
     - "5432:5432"
  front:
    build: ./frontend/.
    volumes:
     - ./frontend/src:/app/src
     - ./resources:/app/output